Close JSDOM after writing HTML
Otherwise I get OOM:

  <--- Last few GCs --->

  [687157:0x55994f317a10]    78136 ms: Mark-Compact (reduce) 4052.3 (4142.7) -> 4026.7 (4142.2) MB, 60.26 / 0.03 ms  (+ 2035.1 ms in 296 steps since start of marking, biggest step 12.7 ms, walltime since start of marking 2818 ms) (average mu = 0.705, curren[687157:0x55994f317a10]    78149 ms: Scavenge 4027.8 (4142.2) -> 4027.7 (4145.2) MB, 9.80 / 0.00 ms  (average mu = 0.705, current mu = 0.789) allocation failure;

  <--- JS stacktrace --->

  FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
   1: 0x55994bc779d8 node::Abort() [node]
   2: 0x55994bb6ea8a  [node]
   3: 0x55994c389640 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
   4: 0x55994c3899d5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
   5: 0x55994c5e9297  [node]
   6: 0x55994c602caf v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
   7: 0x55994c5d55fc v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
   8: 0x55994c5d6895 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
   9: 0x55994c5b1b9e v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
  10: 0x55994ca768a1 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
  11: 0x5598ece5a2b6